services:
  nginx:
    image: nginx:1.26.2-alpine3.20-perl
    container_name: nginx-reverse-proxy
    ports:
      # Порты для Nexus
      - "10443:10443"
      - "127.0.0.1:8084:127.0.0.1:8084"

      # Порты для SonarQube
      - "11443:11443"
      - "127.0.0.1:8085::127.0.0.1:8085"
    volumes:
      - /home/dockeruser/infr/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/dockeruser/infr/nginx/conf.d:/etc/nginx/conf.d
      - /home/dockeruser/infr/nginx/ssl:/etc/nginx/ssl