global:
  scrape_interval: 15s

scrape_configs:
  # Prometheus
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Мониторинг ресурсов машины через Node Exporter
  - job_name: "node_exporter"
    static_configs:
      - targets: ["172.18.130.50:9100"]

  # Мониторинг контейнеров через cAdvisor
  - job_name: "cadvisor"
    static_configs:
      - targets: ["172.18.130.50:8080"]

  # Мониторинг Gitlab и Nexus на портах 9443 и 127.0.0.1:8084
  - job_name: "custom_services"
    static_configs:
      - targets:
          - "172.18.130.50:9443"
          - "127.0.0.1:8084"
